<a href="https://colab.research.google.com/github/mskang222/NLP_2023/blob/main/11%EC%9B%94_26%EC%9D%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

랜덤포레스트_손글씨분류(2)

In [1]:
from sklearn import datasets
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# sklearn 모델의 동일한 결과 출력을 위해 선언합니다.
np.random.seed(5)

In [2]:
#손글씨 데이터 로드
mnist = datasets.load_digits()
features, labels = mnist.data, mnist.target

In [3]:
features

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [4]:
labels  #features 정답

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
#교차 검증
def cross_validation(classifier,features, labels):
    cv_scores = []

    for i in range(10):
        scores = cross_val_score(classifier,features, labels,cv=10,scoring='accuracy')
        cv_scores.append(scores.mean())

    return cv_scores # 10 개의 값이 반환될것임

In [6]:
dt_cv_scores = cross_validation(tree.DecisionTreeClassifier(), features, labels)

In [7]:
rf_cv_scores = cross_validation(RandomForestClassifier(), features, labels)

cv_list = [
            ['random_forest',rf_cv_scores],
            ['decision_tree',dt_cv_scores]
          ]
#df = pd.DataFrame.from_items(cv_list)

df = pd.DataFrame(cv_list)

In [9]:
cv_list = [
            ['random_forest',rf_cv_scores],
            ['decision_tree',dt_cv_scores]
          ]
#df = pd.DataFrame.from_items(cv_list)

df = pd.DataFrame(cv_list)

In [11]:
df   #랜덤포레스트가 의사결정트리보다 매번 정확도가 높은 것을 확인할 수 있다.

0                                                  1
0  random_forest  [0.9526939788950962, 0.9487957790192427, 0.951...
1  decision_tree  [0.8280229671011794, 0.8235630043451273, 0.822...

In [12]:
df.shape

(2, 2)

In [13]:
cv_list

[['random_forest',
  [0.9526939788950962,
   0.9487957790192427,
   0.9510211049037863,
   0.9549286157666046,
   0.9471322160148976,
   0.9487988826815641,
   0.952122905027933,
   0.9454531346989447,
   0.9460180012414648,
   0.9471322160148976]],
 ['decision_tree',
  [0.8280229671011794,
   0.8235630043451273,
   0.8224674115456239,
   0.8235692116697703,
   0.8341464928615766,
   0.8185692116697704,
   0.8241247672253259,
   0.8180136561142148,
   0.8235630043451272,
   0.8258038485412786]]]

In [15]:
RF=np.array(cv_list[0][1])

In [16]:
RF

array([0.95269398, 0.94879578, 0.9510211 , 0.95492862, 0.94713222,
       0.94879888, 0.95212291, 0.94545313, 0.946018  , 0.94713222])

In [17]:
cv_list[1][0]

'decision_tree'

In [18]:
cv_list[1][1]

[0.8280229671011794,
 0.8235630043451273,
 0.8224674115456239,
 0.8235692116697703,
 0.8341464928615766,
 0.8185692116697704,
 0.8241247672253259,
 0.8180136561142148,
 0.8235630043451272,
 0.8258038485412786]

In [19]:
DT=np.array(cv_list[1][1])

In [21]:
DT

array([0.82802297, 0.823563  , 0.82246741, 0.82356921, 0.83414649,
       0.81856921, 0.82412477, 0.81801366, 0.823563  , 0.82580385])

In [22]:
df=pd.DataFrame(columns=['RF','DT'])
df['RF']=RF
df['DT']=DT
df

RF        DT
0  0.952694  0.828023
1  0.948796  0.823563
2  0.951021  0.822467
3  0.954929  0.823569
4  0.947132  0.834146
5  0.948799  0.818569
6  0.952123  0.824125
7  0.945453  0.818014
8  0.946018  0.823563
9  0.947132  0.825804

In [23]:
np.mean(dt_cv_scores) #의사결정트리 정확도

0.8241843575418993

In [24]:
np.mean(rf_cv_scores) #랜덤포레스트 정확

0.9494096834264433

random Forest 하이퍼 파라미터 튜닝

In [25]:
rf_cv_scores = cross_validation(RandomForestClassifier(), features, labels)

In [26]:
np.mean(rf_cv_scores)

0.9483488516449409